# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chat_app_development
  username: myuser
  password: mypassword
  host: localhost

test:
  <<: *default
  database: chat_app_test
  username: myuser
  password: mypassword
  host: localhost

production:
  <<: *default
  database: chat_app_production
  username: myuser
  password: <%= ENV['CHAT_APP_DATABASE_PASSWORD'] %>
  host: localhost



